config/routes.rb
Rails.application.routes.draw do




 

  
  resources :subscribers
  root 'pages#index'
  get 'admin' => 'admin/dashboard#index'


  namespace :admin do
    resource :dashboard, only: [:index]
    resources :users
    resources :prizes
    resources :conditions
    
  end




  devise_for :users
  
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/condition.rb
class Admin::Condition < ActiveRecord::Base

	belongs_to :prize
end

app/models/admin/multiples_condition.rb
class Admin::MultiplesCondition < Condition::Admin
  hstore_accessor :additional_data,
    multiple: :integer,
    from: :integer

  def matches(subscriber)
    if subscriber.id > from
      subscriber.id % multiple == 0
    else
      false
    end
  end
end

app/models/admin/prize.rb
class Admin::Prize < ActiveRecord::Base

	has_one :condition
end

app/models/admin/subscriber_list_condition.rb
class Admin::SubscriberListCondition < Condition::Admin
  hstore_accessor :data,
    ids: :string

  def matches(subscriber)
    ids.split(",").include?(subscriber.id)
  end
end

app/models/subscriber.rb
# == Schema Information
#
# Table name: subscribers
#
#  id         :integer          not null, primary key
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Subscriber < ActiveRecord::Base
	
	
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  admin                  :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


         
end

app/controllers/admin/conditions_controller.rb
class Admin::ConditionsController < ApplicationController
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  


 before_action :authenticate_user!

  layout "admin"
  def index
  	@admin_prizes = Admin::Prize.all
  end


  
end

app/controllers/admin/prizes_controller.rb
class Admin::PrizesController < ApplicationController
  before_action :set_admin_prize, only: [:show, :edit, :update, :destroy]


   layout "admin"
  # GET /admin/prizes/1
  # GET /admin/prizes/1.json
  def show

    @admin_condition = Admin::Condition.new
  end

  # GET /admin/prizes/new
  def new
    @admin_prize = Admin::Prize.new
  end

  # GET /admin/prizes/1/edit
  def edit
  end

  # POST /admin/prizes
  # POST /admin/prizes.json
  def create
    @admin_prize = Admin::Prize.new(admin_prize_params)

    respond_to do |format|
      if @admin_prize.save
        format.html { redirect_to @admin_prize, notice: 'Prize was successfully created.' }
        format.json { render :show, status: :created, location: @admin_prize }
      else
        format.html { render :new }
        format.json { render json: @admin_prize.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/prizes/1
  # PATCH/PUT /admin/prizes/1.json
  def update
    respond_to do |format|
      if @admin_prize.update(admin_prize_params)
        format.html { redirect_to @admin_prize, notice: 'Prize was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_prize }
      else
        format.html { render :edit }
        format.json { render json: @admin_prize.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/prizes/1
  # DELETE /admin/prizes/1.json
  def destroy
    @admin_prize.destroy
    respond_to do |format|
      format.html { redirect_to admin_prizes_url, notice: 'Prize was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_prize
      @admin_prize = Admin::Prize.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_prize_params
      params.require(:admin_prize).permit(:name, :description, :amount)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


	def index

		@subscriber = Subscriber.new
		
	end


end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

	private
	def sign_up_params
	  params.require(:user).permit(:email, :password, :time_zone)
	end

	def account_update_params
	  params.require(:user).permit(:email, :password, :current_password, :time_zone)
	end

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController


  def create
    @subscriber = Subscriber.new(subscriber_params)
    @subscriber.save
    flash[:sucess] = 'Se ha suscrito con exitó a nuestra base de datos'
    redirect_to root_path
  end

  private

  def subscriber_params
  	params.require(:subscriber).permit(:email)
  end

end

app/helpers/admin/conditions_helper.rb
module Admin::ConditionsHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/prizes_helper.rb
module Admin::PrizesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/admin/conditions/_form.html.erb
<%= form_for(@admin_condition) do |f| %>  
        <% if @admin_condition.errors.any? %>  
        <div id="error_explanation">
          <h2><%= pluralize(@admin_condition.errors.count, "error") %> prohibited this admin_condition from being saved:</h2>
          <ul>
            <% @admin_condition.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <div class="form-group">
          <%= f.label :type %><br>
          <%= f.collection_select :type, Type.all, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :data %><br>
          <%= f.text_area :data, class:"form-control"  %>
        </div>
      
        <div class="from-group">
          <%= f.submit class: "btn btn-primary" %>
        </div>    
<% end %>    

app/views/admin/dashboard/index.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading text-center"> <strong>Listado de Premios y Disponibilidad</strong></div>

    <!-- Table -->
  <table class="table">
	<thead>
	  <tr>
	    <th>Name</th>
	    <th>Description</th>
	    <th>Amount</th>
	    <th colspan="3"></th>
	  </tr>
	</thead>
	<tbody>
	  <% @admin_prizes.each do |admin_prize| %>
	    <tr>
	      <td><%= admin_prize.name %></td>
	      <td><%= admin_prize.description %></td>
	      <td>
	      	<%= admin_prize.amount %>
	      	<%= link_to 'Show', admin_prize %>
	      	<%= link_to 'Edit', edit_admin_prize_path(admin_prize) %>
	      	<%= link_to 'Destroy', admin_prize, method: :delete, data: { confirm: 'Are you sure?' } %>
	      </td>	      
	    </tr>
	  <% end %>
	</tbody>    
  </table>
</div>

app/views/admin/prizes/_form.html.erb
<%= form_for(@admin_prize) do |f| %>  
        <% if @admin_prize.errors.any? %>  
        <div id="error_explanation">
          <h2><%= pluralize(@admin_prize.errors.count, "error") %> prohibited this admin_prize from being saved:</h2>
          <ul>
            <% @admin_prize.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description %><br>
          <%= f.text_area :description, class:"form-control"  %>
        </div>
        <div class="form-group">
          <%= f.label :amount %><br>
          <%= f.text_field :amount, class:"form-control"  %>
        </div>
        <div class="from-group">
          <%= f.submit "Crear Premio", class: "btn btn-primary" %>
        </div>    
<% end %>    

app/views/admin/prizes/_form_condition.html.erb
<%= form_for(@admin_condition) do |f| %>  
        <% if @admin_condition.errors.any? %>  
        <div id="error_explanation">
          <h2><%= pluralize(@admin_condition.errors.count, "error") %> prohibited this admin_condition from being saved:</h2>
          <ul>
            <% @admin_condition.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <div class="form-group">
          <%= f.label :type %><br>
          <%= f.text_field :type, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :data %><br>
          <%= f.text_area :data, class:"form-control"  %>
        </div>
      
        <div class="from-group">
          <%= f.submit class: "btn btn-primary" %>
        </div>    
<% end %>    

app/views/admin/prizes/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">	
		<div class="panel panel-default">            
		    <div class="panel-heading">
		      <h1>Editar Premio</h1>     
		    </div>
		    <div class="panel-body">                
		     <%= render 'form' %>	 
		   </div>   
		    <div class="panel-footer">
		      <%= link_to 'Ver', @admin_prize %> |	
		      <%= link_to 'Regresar', admin_path %>
		    </div>    
		</div>
	</div>
</div>

app/views/admin/prizes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Prizes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_prizes.each do |admin_prize| %>
      <tr>
        <td><%= admin_prize.name %></td>
        <td><%= admin_prize.description %></td>
        <td><%= admin_prize.amount %></td>
        <td><%= link_to 'Show', admin_prize %></td>
        <td><%= link_to 'Edit', edit_admin_prize_path(admin_prize) %></td>
        <td><%= link_to 'Destroy', admin_prize, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prize', new_admin_prize_path %>

app/views/admin/prizes/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">	
		<div class="panel panel-default">            
		    <div class="panel-heading">
		      <h1>Nuevo Premio</h1>     
		    </div>
		    <div class="panel-body">                
		     <%= render 'form' %>	 
		   </div>   
		    <div class="panel-footer">
		      <%= link_to 'Regresar', admin_path %>
		    </div>    
		</div>
	</div>
</div>

app/views/admin/prizes/show.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">	
		<div class="panel panel-default">
			<p id="notice"><%= notice %></p>            
		    <div class="panel-heading">
				<p>
				  <strong>Name:</strong>
				  <%= @admin_prize.name %>
				</p>		        
		    </div>
		    <div class="panel-body"> 
				<p>
				  <strong>Description:</strong>
				  <%= @admin_prize.description %>
				</p>

				<p>
				  <strong>Amount:</strong>
				  <%= @admin_prize.amount %>
				</p>
		   </div>   

			

			<%= render "form_condition" %>


		    <div class="panel-footer">
		    	<%= link_to 'Editar', edit_admin_prize_path(@admin_prize) %> |		 
		        <%= link_to 'Regresar', admin_path %>
		    </div>    
		</div>
	</div>
</div>